name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check files
        run: ls -R

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore $(find . -name "*.sln" | head -n 1)

      - name: Build
        run: dotnet build $(find . -name "*.sln" | head -n 1) --configuration Release

      - name: Test
        run: dotnet test $(find . -name "*.sln" | head -n 1) --logger "trx"

      - name: TODO Deployment
        run: echo "TODO – Deployment"
