name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Find solution file
        run: find . -name "*.sln"

      - name: Restore dependencies
        run: dotnet restore $(find . -name "*.sln")

      - name: Build
        run: dotnet build $(find . -name "*.sln") --configuration Release --no-restore

      - name: Test
        run: dotnet test $(find . -name "*.sln") --logger "trx"

      - name: TODO Deployment
        run: echo "TODO – Deployment"
